kind: Service
apiVersion: v1
metadata:
  name: python-ptds-service-prod
  namespace: production-namespace
  labels:
    app: python-ptds
    version: jenkins-will-replace
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: python-ptds
