kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: python-ptds
  namespace: ${execution['stages'][1]['name']}
spec:
  replicas: 3
  template:
    metadata:
      name: python-ptds
      labels:
        app: python-ptds
        version: spinnaker-will-replace
    spec:
      containers:
      - name: python-ptds-image
        image: gmurra11/python-ptds
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ptds
            port: 5000
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - name: python-ptds
          containerPort: 80
